What is Tensoflow?
- Tensorflow is an open-source framework developed by Google use for AI, ML DL.

**TensorFlow Python API**
* tensorflow - The core package for low-level operations
* tensorflow.keras - A high-level API for building neural networks
* tensorflow.data - Helps you with data input pipelines
* tensorflow.estimator - A more scalable API for production-level tasks
* tensorflow_hub - For reusable machine learning modules

In [3]:
# tensorflow API
import tensorflow as tf
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
result = tf.add(a,b)
print(result)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [5]:
# Tensorflow Keras APU
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(units=64, activation='relu', input_dim=100),
    Dense(units=10, activation='softmax')
])

model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])



In [7]:
# Tensorflow data API
import tensorflow as tf
dataset = tf.data.Dataset.from_tensor_slices(([1,2,3,4]))
dataset = dataset.batch(2)

for batch in dataset:
    print(batch)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)


In [10]:
# Tensorflow Estimator API
# from tensorflow.estimator import Estimator

# def model_fn(features, labels, mode):
#     # Define your model function here
#     pass

# classifier = Estimator(model_fn=model_fn)


In [11]:
# Tensorflow  hub API
import tensorflow_hub as hub

model = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4")


In [13]:
# tensorflow Lite API

import tensorflow as tf

# model = tf.keras.models.load_model('my_model.h5')
# converter = tf.lite.TFLiteConverter.from_keras_model(model)
# tflite_model = converter.convert()


**To summarize, we covered:**

* tensorflow: Low-level API for tensor operations
* tensorflow.keras: High-level API for building neural networks
* tensorflow.data: For data input pipelines
* tensorflow.estimator: Scalable API for production-level tasks
* tensorflow_hub: Pre-trained models for reuse
* tensorflow.lite: Deploying models on mobile and edge devices